version: "3"

volumes:
  postgres-data:

services:
  db:
    image: postgres:10
    environment:
      POSTGRES_USER: ledger
      POSTGRES_PASSWORD: ledger
      POSTGRES_DATABASE: ledger_dev
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432